import { Card } from "@/components/ui/card"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"

export default function FAQPage() {
  return (
    <div className="container py-12">
      <div className="text-center mb-8">
        <h1 className="text-3xl font-bold">Frequently Asked Questions</h1>
        <p className="text-muted-foreground mt-2">Find answers to common questions about IdeaForge</p>
      </div>

      <Accordion type="single" collapsible className="w-full">
        <Card className="mb-4">
          <AccordionItem value="item-1">
            <AccordionTrigger>What is IdeaForge?</AccordionTrigger>
            <AccordionContent>
              IdeaForge is a platform designed to help you capture, develop, and implement innovative ideas. It provides
              tools for collaboration, market research, and project management.
            </AccordionContent>
          </AccordionItem>
        </Card>

        <Card className="mb-4">
          <AccordionItem value="item-2">
            <AccordionTrigger>How do I create a new idea?</AccordionTrigger>
            <AccordionContent>
              To create a new idea, navigate to the "Ideas Hub" and click on the "Create New Idea" button. Fill out the
              form with your idea details, including title, description, category, and tags.
            </AccordionContent>
          </AccordionItem>
        </Card>

        <Card className="mb-4">
          <AccordionItem value="item-3">
            <AccordionTrigger>How can I collaborate with others on an idea?</AccordionTrigger>
            <AccordionContent>
              You can invite collaborators to your idea by adding their email addresses in the "Collaborators" field
              when creating or editing an idea. Collaborators can view, comment, and contribute to the idea.
            </AccordionContent>
          </AccordionItem>
        </Card>

        <Card className="mb-4">
          <AccordionItem value="item-4">
            <AccordionTrigger>What is the project conversion workflow?</AccordionTrigger>
            <AccordionContent>
              The project conversion workflow allows you to transform an idea into a structured project with defined
              resources, timeline, and objectives. To convert an idea, click on the "Convert to Project" button on the
              idea card.
            </AccordionContent>
          </AccordionItem>
        </Card>

        <Card className="mb-4">
          <AccordionItem value="item-5">
            <AccordionTrigger>How do I request approval for an idea?</AccordionTrigger>
            <AccordionContent>
              To request approval for an idea, navigate to the idea details page and click on the "Request Approval"
              button. Select the approvers and add a message, then submit the request.
            </AccordionContent>
          </AccordionItem>
        </Card>

        <Card className="mb-4">
          <AccordionItem value="item-6">
            <AccordionTrigger>What are AI insights and how do I use them?</AccordionTrigger>
            <AccordionContent>
              AI insights are generated by our quantum-powered AI to provide recommendations, identify potential
              challenges, and suggest implementation strategies. You can view AI insights on the idea details page.
            </AccordionContent>
          </AccordionItem>
        </Card>

        <Card className="mb-4">
          <AccordionItem value="item-7">
            <AccordionTrigger>How do I manage my account settings?</AccordionTrigger>
            <AccordionContent>
              To manage your account settings, click on your profile icon in the header and select "Settings" from the
              dropdown menu. You can update your profile information, change your password, and manage notification
              preferences.
            </AccordionContent>
          </AccordionItem>
        </Card>
      </Accordion>
    </div>
  )
}
